// The web app's own words in Hindi, written by hand. Keys are the English text used in the web files.
export const HI = {
  "{n} of {m} saved": "{m} में से {n} सेव",
  "Add my details": "मेरी जानकारी जोड़ें",
  "What we keep": "हम क्या रखते हैं",
  "Your place in the guide and your language, deleted after a few hours of inactivity. Details you choose to save (name, date of birth, parents’ names, gender, address, PIN code, mobile number, email) are stored encrypted until you delete them. The locker keeps ID numbers and expiry dates, encrypted, hidden until you unlock. We never store Aadhaar card photos, card numbers or OTPs.": "गाइड में आपकी जगह और आपकी भाषा, कुछ घंटे निष्क्रिय रहने पर हट जाती है। जो जानकारी आप सेव करना चुनते हैं (नाम, जन्म तारीख, माता-पिता के नाम, लिंग, पता, पिन कोड, मोबाइल नंबर, ईमेल) वह आपके हटाने तक एन्क्रिप्ट करके रखी जाती है। लॉकर में आईडी नंबर और समाप्ति की तारीखें एन्क्रिप्टेड रहती हैं और अनलॉक करने तक छिपी रहती हैं। हम आधार कार्ड की फोटो, कार्ड नंबर या OTP कभी सेव नहीं करते।",
  "Photos, PDFs and voice notes": "फोटो, PDF और वॉइस नोट",
  "Only read if you agree, held in memory and never saved. Voice notes are turned into text by a speech service and the audio is not kept.": "आपकी सहमति से ही पढ़े जाते हैं, केवल मेमोरी में रहते हैं और सेव नहीं होते। वॉइस नोट को स्पीच सेवा टेक्स्ट में बदलती है और ऑडियो नहीं रखा जाता।",
  "If you set one, we keep its date, its name and your phone number (encrypted) so we can message you before it.": "अगर आप रिमाइंडर लगाते हैं, तो हम उसकी तारीख, नाम और आपका फोन नंबर (एन्क्रिप्टेड) रखते हैं ताकि उससे पहले आपको संदेश भेज सकें।",
  "Payments": "भुगतान",
  "Paid on Razorpay’s own page. We never see your card or UPI details. We keep the amount, date and reference for your wallet.": "भुगतान Razorpay के अपने पेज पर होता है। हम आपके कार्ड या UPI की जानकारी कभी नहीं देखते। वॉलेट के लिए हम राशि, तारीख और संदर्भ रखते हैं।",
  "AI": "AI",
  "Free-form questions, document reading and translation are processed by an AI service. Your saved details are never sent to it. Languages other than English and Hindi are machine translated and may have mistakes.": "खुले सवाल, दस्तावेज़ पढ़ना और अनुवाद एक AI सेवा से होते हैं। आपकी सेव की हुई जानकारी उसे कभी नहीं भेजी जाती। अंग्रेज़ी और हिंदी के अलावा भाषाएँ मशीन से अनुवादित हैं और उनमें गलतियाँ हो सकती हैं।",
  "What we never do": "हम कभी क्या नहीं करते",
  "We never ask for your OTP or password. Do not share them with anyone. Everything is stored under a scrambled ID, not your phone number.": "हम आपका OTP या पासवर्ड कभी नहीं माँगते। इन्हें किसी से साझा न करें। सब कुछ एक अलग आईडी के नीचे रखा जाता है, आपके फोन नंबर के नहीं।",
  "Deleting your data": "अपना डेटा हटाना",
  "Settings, then Delete all my data, removes your saved details, locker, reminders and wallet from our server.": "सेटिंग्स में “मेरा सारा डेटा हटाएँ” से आपकी सेव की हुई जानकारी, लॉकर, रिमाइंडर और वॉलेट हमारे सर्वर से हट जाते हैं।",
  "What Saathi keeps, what it never does, and how to delete it all.": "साथी क्या रखता है, क्या कभी नहीं करता, और सब कैसे हटाएँ।",
  "Close": "बंद करें",
  'Official': 'आधिकारिक',
  'Pay securely on Razorpay': 'Razorpay पर सुरक्षित भुगतान करें',
  'Looks like a trap': 'यह जाल जैसा लगता है',
  'Not confirmed official': 'आधिकारिक होने की पुष्टि नहीं',
  'Copied': 'कॉपी हो गया',
  'Copied. Paste it into the official site.': 'कॉपी हो गया। इसे आधिकारिक साइट पर पेस्ट करें।',
  'Copy all': 'सब कॉपी करें',
  'Your details': 'आपकी जानकारी',
  'Copy-ready, one tap each': 'कॉपी के लिए तैयार, हर एक पर एक टैप',
  'Copy': 'कॉपी',
  'Still needed': 'अभी चाहिए',
  'Type or paste these into the official website yourself. Saathi never logs in for you, and never sees your OTP.': 'इन्हें खुद आधिकारिक वेबसाइट पर टाइप या पेस्ट करें। साथी आपकी जगह लॉग इन नहीं करता और आपका OTP कभी नहीं देखता।',
  'Hide': 'छिपाएँ',
  'Locker': 'लॉकर',
  'Unlocked for {n} seconds': '{n} सेकंड के लिए खुला है',
  'Nothing here is saved on this device. It hides on its own.': 'यहाँ कुछ भी इस डिवाइस पर सेव नहीं होता। यह अपने आप छिप जाता है।',
  'Hidden again. Ask me again, or tap Unlock above, to see it.': 'फिर से छिप गया। देखने के लिए दोबारा पूछें या ऊपर अनलॉक दबाएँ।',
  'Saathi is typing': 'साथी लिख रहा है',
  'Try again': 'फिर कोशिश करें',
  'Still working on it…': 'अभी काम जारी है…',
  'You are going a little fast. Wait a few seconds and try again.': 'आप थोड़ा तेज़ जा रहे हैं। कुछ सेकंड रुककर फिर कोशिश करें।',
  'That upload expired. Please attach it again.': 'वह अपलोड खत्म हो गया। कृपया दोबारा जोड़ें।',
  'Something went wrong on our side. Nothing was lost.': 'हमारी तरफ़ कुछ गड़बड़ हुई। कुछ भी खोया नहीं।',
  'No internet connection. Check it and try again.': 'इंटरनेट नहीं है। जाँचकर फिर कोशिश करें।',
  'I can read photos and PDF files. Try one of those.': 'मैं फ़ोटो और PDF फ़ाइल पढ़ सकता हूँ। इनमें से कोई भेजें।',
  'That file is too big. Try a smaller photo or PDF.': 'वह फ़ाइल बहुत बड़ी है। छोटी फ़ोटो या PDF भेजें।',
  'That file is too big after shrinking. Try a smaller PDF, or a photo.': 'छोटा करने के बाद भी फ़ाइल बड़ी है। छोटी PDF या फ़ोटो भेजें।',
  'Sent a PDF': 'PDF भेजी',
  'Sent a photo': 'फ़ोटो भेजी',
  'That kind of file is not supported.': 'इस तरह की फ़ाइल चल नहीं सकती।',
  'Slow down a little, then try again.': 'थोड़ा धीरे चलें, फिर कोशिश करें।',
  'The upload failed. Check your connection and try again.': 'अपलोड नहीं हुआ। कनेक्शन जाँचकर फिर कोशिश करें।',
  'I could not use the microphone. Allow it in your browser settings, or just type.': 'माइक्रोफ़ोन नहीं चल पाया। ब्राउज़र सेटिंग में उसे इजाज़त दें, या बस टाइप करें।',
  'Listening… speak now': 'सुन रहा हूँ… अब बोलिए',
  'Change the language you speak': 'बोलने की भाषा बदलें',
  'Recording. Tap send when you are done.': 'रिकॉर्डिंग चल रही है। पूरा होने पर भेजें दबाएँ।',
  'Stop and send voice message': 'रोकें और वॉइस मैसेज भेजें',
  'Voice message': 'वॉइस मैसेज',
  'The voice message did not upload. Try again, or type instead.': 'वॉइस मैसेज अपलोड नहीं हुआ। फिर कोशिश करें, या टाइप करें।',
  'Send': 'भेजें',
  'How do I apply for a new PAN card?': 'नया पैन कार्ड कैसे बनवाऊँ?',
  'My PAN has a wrong name. How do I fix it?': 'मेरे पैन में नाम गलत है। कैसे ठीक करूँ?',
  'How do I update the address in my Aadhaar?': 'आधार में पता कैसे बदलूँ?',
  'What do I need for a driving licence?': 'ड्राइविंग लाइसेंस के लिए क्या चाहिए?',
  'How do I renew my passport?': 'पासपोर्ट कैसे रिन्यू करूँ?',
  'How do I add my name to the voter list?': 'वोटर लिस्ट में नाम कैसे जुड़वाऊँ?',
  'Do I need GST registration for a small shop?': 'छोटी दुकान के लिए क्या GST रजिस्ट्रेशन चाहिए?',
  'How do I get an income certificate?': 'आय प्रमाण पत्र कैसे बनवाऊँ?',
  'How do I apply for a caste certificate?': 'जाति प्रमाण पत्र के लिए आवेदन कैसे करूँ?',
  'Hi, I’m Saathi.': 'नमस्ते, मैं साथी हूँ।',
  'I help with government paperwork: PAN, Aadhaar, driving licence, passport and more. Just tell me what you need in your own words, or try one of these.': 'मैं सरकारी कागज़ात में मदद करता हूँ: पैन, आधार, ड्राइविंग लाइसेंस, पासपोर्ट और बहुत कुछ। बस अपनी बात अपने शब्दों में लिखिए, या इनमें से कोई चुनिए।',
  'Is this SMS or link real?': 'क्या यह SMS या लिंक असली है?',
  'Open my locker': 'मेरा लॉकर खोलें',
  'English': 'अंग्रेज़ी',
  'PAN card': 'पैन कार्ड',
  'Aadhaar': 'आधार',
  'Driving licence': 'ड्राइविंग लाइसेंस',
  'Passport': 'पासपोर्ट',
  'Voter ID': 'वोटर आईडी',
  'GST registration': 'GST रजिस्ट्रेशन',
  'Income certificate': 'आय प्रमाण पत्र',
  'Caste certificate': 'जाति प्रमाण पत्र',
  'How do I fix a wrong name on my PAN?': 'पैन में गलत नाम कैसे ठीक करूँ?',
  'How do I update my address in Aadhaar?': 'आधार में अपना पता कैसे बदलूँ?',
  'Do I start with a learner licence?': 'क्या पहले लर्नर लाइसेंस बनवाना होगा?',
  'Is this a fresh passport or a renewal?': 'यह नया पासपोर्ट है या रिन्यूअल?',
  'How do I check my name in the voter list?': 'वोटर लिस्ट में अपना नाम कैसे देखूँ?',
  'Do I need GST registration for my work?': 'क्या मेरे काम के लिए GST रजिस्ट्रेशन चाहिए?',
  'Where do I apply for an income certificate?': 'आय प्रमाण पत्र के लिए आवेदन कहाँ करूँ?',
  'Which proof is accepted for a caste certificate?': 'जाति प्रमाण पत्र के लिए कौन सा सबूत चलता है?',
  '*{name}*': '*{name}*',
  'Official fee: {fee}': 'आधिकारिक फीस: {fee}',
  'Ask me anything about this, or let me guide you step by step.': 'इस बारे में कुछ भी पूछिए, या मुझे कदम-दर-कदम रास्ता दिखाने दीजिए।',
  'What documents do I need?': 'मुझे कौन से दस्तावेज़ चाहिए?',
  'How much does it cost?': 'इसमें कितना खर्च आएगा?',
  'Guide me step by step': 'कदम-दर-कदम गाइड करें',
  'What should I know first?': 'सबसे पहले मुझे क्या जानना चाहिए?',
  'Full details': 'पूरी जानकारी',
  'Recent': 'हाल की चैट',
  'New chat': 'नई चैट',
  'Delete this chat': 'यह चैट हटाएँ',
  'All chats': 'सभी चैट',
  'Close menu': 'मेन्यू बंद करें',
  'Services': 'सेवाएँ',
  'All services': 'सभी सेवाएँ',
  'Tools': 'औज़ार',
  'Scan a document': 'दस्तावेज़ स्कैन करें',
  'Form sheet': 'फ़ॉर्म शीट',
  'Make my form sheet': 'मेरी फ़ॉर्म शीट बनाएँ',
  'My locker': 'मेरा लॉकर',
  'Reminders': 'रिमाइंडर',
  'Is this real?': 'क्या यह असली है?',
  'Wallet': 'वॉलेट',
  'Settings': 'सेटिंग्स',
  'Help and support': 'मदद और सहायता',
  'Privacy': 'गोपनीयता',
  'Not a government website': 'सरकारी वेबसाइट नहीं है',
  'Back': 'वापस',
  'Welcome credit': 'स्वागत क्रेडिट',
  'Money added': 'पैसे जुड़े',
  'Guide message': 'गाइड मैसेज',
  'AI answer': 'AI जवाब',
  'Document check': 'दस्तावेज़ जाँच',
  'Voice note': 'वॉइस नोट',
  'Reminder': 'रिमाइंडर',
  'Pack bought': 'पैक खरीदा',
  'Refund': 'रिफ़ंड',
  'Other': 'अन्य',
  'Quick pack': 'क्विक पैक',
  'Saathi pack': 'साथी पैक',
  'Saathi Plus': 'साथी प्लस',
  'Your balance, packs and recent activity.': 'आपका बैलेंस, पैक और हाल की गतिविधि।',
  'Balance': 'बैलेंस',
  '{left} of {total} free guide messages left today': 'आज {total} में से {left} मुफ़्त गाइड मैसेज बाकी हैं',
  '{left} of {total} free AI answers left today': 'आज {total} में से {left} मुफ़्त AI जवाब बाकी हैं',
  'Add money': 'पैसे जोड़ें',
  'See packs': 'पैक देखें',
  '{name} is on': '{name} चालू है',
  'Active': 'चालू',
  'Until {date}. Guide messages and form sheets are unlimited.': '{date} तक। गाइड मैसेज और फ़ॉर्म शीट असीमित हैं।',
  'document checks left': 'दस्तावेज़ जाँच बाकी',
  'AI answers left': 'AI जवाब बाकी',
  'voice notes left': 'वॉइस नोट बाकी',
  'reminders left': 'रिमाइंडर बाकी',
  'Recent activity': 'हाल की गतिविधि',
  'See all': 'सब देखें',
  'Nothing yet. Charges and top-ups will show here.': 'अभी कुछ नहीं। खर्च और टॉप-अप यहाँ दिखेंगे।',
  'Guide message (after the free ones)': 'गाइड मैसेज (मुफ़्त वालों के बाद)',
  'AI answer (after the free ones)': 'AI जवाब (मुफ़्त वालों के बाद)',
  'Pay per use': 'इस्तेमाल के हिसाब से भुगतान',
  'Free messages renew every day. Saathi never charges without showing the price first.': 'मुफ़्त मैसेज हर दिन नए मिलते हैं। साथी कीमत दिखाए बिना कभी पैसे नहीं काटता।',
  'Transactions': 'लेन-देन',
  'Everything that went in or out of your wallet.': 'आपके वॉलेट में आया और गया सब कुछ।',
  'No activity yet': 'अभी कोई गतिविधि नहीं',
  'Charges, top-ups and refunds will appear here.': 'खर्च, टॉप-अप और रिफ़ंड यहाँ दिखेंगे।',
  'Open the secure Razorpay page to pay {amt}. Come back here when you are done. This page updates by itself.': '{amt} चुकाने के लिए सुरक्षित Razorpay पेज खोलें। पूरा होने पर यहाँ लौट आएँ। यह पेज अपने आप बदल जाएगा।',
  'Open Razorpay to pay {amt}': '{amt} चुकाने के लिए Razorpay खोलें',
  'Waiting for your payment…': 'आपके भुगतान का इंतज़ार है…',
  'I have paid, check now': 'मैंने भुगतान कर दिया, अभी जाँचें',
  'Cancel': 'रद्द करें',
  'Not received yet. It can take a minute after you pay.': 'अभी नहीं मिला। भुगतान के बाद एक मिनट लग सकता है।',
  'Still waiting. If you paid, tap the button above in a moment.': 'अभी इंतज़ार है। अगर आपने भुगतान किया है तो थोड़ी देर में ऊपर का बटन दबाएँ।',
  'Done': 'हो गया',
  'Choose an amount. It goes into your wallet and is used only when you use a paid feature.': 'रकम चुनें। यह आपके वॉलेट में जाती है और सिर्फ़ तब कटती है जब आप कोई सशुल्क सुविधा इस्तेमाल करते हैं।',
  'Top-ups are not switched on yet': 'टॉप-अप अभी चालू नहीं हैं',
  'You can keep using Saathi with the free daily messages. Paid features will open once payments go live.': 'आप रोज़ के मुफ़्त मैसेज के साथ साथी इस्तेमाल करते रह सकते हैं। भुगतान शुरू होते ही सशुल्क सुविधाएँ खुल जाएँगी।',
  'Back to wallet': 'वॉलेट पर लौटें',
  'You pay': 'आप चुकाएँगे',
  'Added to wallet': 'वॉलेट में जुड़ेगा',
  'About {ai} AI answers or {scans} document checks.': 'लगभग {ai} AI जवाब या {scans} दस्तावेज़ जाँच।',
  'Pay {amt} securely': '{amt} सुरक्षित चुकाएँ',
  'Preparing your payment…': 'आपका भुगतान तैयार हो रहा है…',
  'We could not start that payment. Nothing was charged. Please try again.': 'वह भुगतान शुरू नहीं हो पाया। कुछ नहीं कटा। कृपया फिर कोशिश करें।',
  'Complete your payment': 'अपना भुगतान पूरा करें',
  'Payment received': 'भुगतान मिल गया',
  '{amt} added. Your balance is now {bal}.': '{amt} जुड़ गए। आपका बैलेंस अब {bal} है।',
  'You pay on Razorpay with UPI, card or netbanking. Saathi never sees your card number or UPI PIN.': 'आप Razorpay पर UPI, कार्ड या नेटबैंकिंग से चुकाते हैं। साथी आपका कार्ड नंबर या UPI PIN कभी नहीं देखता।',
  'Most popular': 'सबसे लोकप्रिय',
  'Best value': 'सबसे किफ़ायती',
  'Packs': 'पैक',
  'One price for a whole paperwork job. No need to count messages.': 'पूरे कागज़ी काम के लिए एक कीमत। मैसेज गिनने की ज़रूरत नहीं।',
  'No packs available': 'कोई पैक उपलब्ध नहीं',
  'Pay-per-use pricing applies.': 'इस्तेमाल के हिसाब से कीमत लगेगी।',
  '{name} is active until {date}. A new pack starts after you buy it.': '{name} {date} तक चालू है। नया पैक खरीदने के बाद शुरू होगा।',
  '{days} days': '{days} दिन',
  'about {amt} a day': 'लगभग {amt} रोज़',
  'Unlimited guide messages': 'असीमित गाइड मैसेज',
  'Unlimited form sheets': 'असीमित फ़ॉर्म शीट',
  '{n} document checks': '{n} दस्तावेज़ जाँच',
  '{n} AI answers': '{n} AI जवाब',
  '{n} voice notes': '{n} वॉइस नोट',
  '{n} reminders': '{n} रिमाइंडर',
  'Get it for {amt} from your wallet': 'वॉलेट से {amt} में लें',
  'Pay {amt} and get it': '{amt} चुकाकर लें',
  'Packs are paid from your wallet. If you are short, you pay only the difference on Razorpay and the pack starts by itself.': 'पैक का पैसा वॉलेट से कटता है। कम पड़े तो बस फ़र्क Razorpay पर चुकाएँ और पैक अपने आप शुरू हो जाएगा।',
  'One moment…': 'एक पल…',
  'It runs until {date}. Enjoy.': 'यह {date} तक चलेगा। आनंद लीजिए।',
  '{name} is on until {date}.': '{name} {date} तक चालू है।',
  '{amt} added. Open Packs again to get it.': '{amt} जुड़ गए। इसे लेने के लिए पैक फिर खोलें।',
  'Search languages': 'भाषा खोजें',
  'No language found. Try another spelling.': 'कोई भाषा नहीं मिली। दूसरी वर्तनी आज़माएँ।',
  'Setting up {lang}': '{lang} तैयार हो रही है',
  'The first time a language is used it takes up to a minute. Later it is instant.': 'किसी भाषा को पहली बार चुनने पर एक मिनट तक लग सकता है। बाद में तुरंत होगा।',
  'Could not change the language. Please try again.': 'भाषा नहीं बदल पाई। कृपया फिर कोशिश करें।',
  'Language': 'भाषा',
  'Everything in the app shows in the language you pick. Saathi answers in the language you write to it, so you can chat in Hindi even if the app is in English.': 'ऐप में सब कुछ आपकी चुनी भाषा में दिखता है। साथी उसी भाषा में जवाब देता है जिसमें आप लिखते हैं, इसलिए ऐप अंग्रेज़ी में हो तब भी आप हिंदी में चैट कर सकते हैं।',
  'Pick a service to chat about it, or open its full details.': 'किसी सेवा के बारे में चैट करने के लिए उसे चुनें, या उसकी पूरी जानकारी खोलें।',
  'Guide, documents and fees': 'गाइड, दस्तावेज़ और फीस',
  'Chat about this': 'इस बारे में चैट करें',
  'Official fee': 'आधिकारिक फीस',
  'What you need': 'आपको क्या चाहिए',
  'Official sites': 'आधिकारिक साइट',
  'Not confirmed by us: {list}. Check the official site.': 'हमारी तरफ़ से पुष्टि नहीं: {list}। आधिकारिक साइट पर जाँचें।',
  'Information last checked {date}.': 'जानकारी आखिरी बार {date} को जाँची गई।',
  'Your conversations are saved on this device.': 'आपकी बातचीत इसी डिवाइस पर सेव है।',
  'No chats yet': 'अभी कोई चैट नहीं',
  'Start a conversation and it will show up here.': 'बातचीत शुरू करें, वह यहाँ दिखेगी।',
  'Delete all chats': 'सभी चैट हटाएँ',
  'Delete all chats?': 'सभी चैट हटाएँ?',
  'This removes the conversations saved on this device. Your wallet and saved details are not touched.': 'इससे इस डिवाइस पर सेव बातचीत हट जाती है। आपका वॉलेट और सेव की हुई जानकारी वैसी ही रहेगी।',
  'Delete chats': 'चैट हटाएँ',
  'Chats deleted': 'चैट हट गईं',
  'Paste an SMS, WhatsApp message or link. Saathi checks it for signs of a scam.': 'कोई SMS, WhatsApp मैसेज या लिंक पेस्ट करें। साथी उसमें ठगी के संकेत जाँचता है।',
  'Paste the message or link here': 'मैसेज या लिंक यहाँ पेस्ट करें',
  'Message to check': 'जाँचने वाला मैसेज',
  'Check it': 'जाँचें',
  'Paste something to check.': 'जाँचने के लिए कुछ पेस्ट करें।',
  'Checking…': 'जाँच रहा हूँ…',
  'Could not check that right now. Please try again.': 'अभी जाँच नहीं हो पाई। कृपया फिर कोशिश करें।',
  'Never share an OTP, PIN or password with anyone, even if they say they are from a government office.': 'OTP, PIN या पासवर्ड किसी को न बताएँ, भले ही वह खुद को सरकारी दफ़्तर से बताए।',
  'Keep the numbers and expiry dates of your PAN, licence, passport and more. Saathi reminds you before they run out.': 'अपने पैन, लाइसेंस, पासपोर्ट आदि के नंबर और खत्म होने की तारीखें रखें। खत्म होने से पहले साथी आपको याद दिलाएगा।',
  'Unlock my locker': 'मेरा लॉकर अनलॉक करें',
  'Add my first document': 'मेरा पहला दस्तावेज़ जोड़ें',
  'Encrypted before it is saved. Only you can open it with the Unlock button': 'सेव होने से पहले एन्क्रिप्ट होता है। सिर्फ़ आप अनलॉक बटन से खोल सकते हैं',
  'Hidden again by itself after a short time': 'थोड़ी देर बाद अपने आप फिर छिप जाता है',
  'Never shown in your chat history or kept on this device': 'चैट इतिहास में कभी नहीं दिखता और इस डिवाइस पर नहीं रखा जाता',
  'You can delete it any time, from here or in Settings': 'आप इसे कभी भी हटा सकते हैं, यहाँ से या सेटिंग्स में',
  'How it stays safe': 'यह सुरक्षित कैसे रहता है',
  'Also': 'और',
  'Saved details': 'सेव की हुई जानकारी',
  'Name, date of birth and address are saved': 'नाम, जन्मतिथि और पता सेव हैं',
  'Nothing saved yet': 'अभी कुछ सेव नहीं',
  'My saved details': 'मेरी सेव की हुई जानकारी',
  'Add the expiry date of a licence, passport or PAN update and Saathi reminds you in time.': 'लाइसेंस, पासपोर्ट या पैन अपडेट की आखिरी तारीख जोड़ें, साथी समय पर याद दिलाएगा।',
  'Add a reminder': 'रिमाइंडर जोड़ें',
  'No reminders yet': 'अभी कोई रिमाइंडर नहीं',
  'Nothing is coming up.': 'आगे कुछ नहीं है।',
  '{n} days ago': '{n} दिन पहले',
  'Today': 'आज',
  'Tomorrow': 'कल',
  'In {n} days': '{n} दिन में',
  'Remove a reminder': 'रिमाइंडर हटाएँ',
  'Reminders are delivered on WhatsApp. Chat with Saathi there once so it can reach you.': 'रिमाइंडर WhatsApp पर आते हैं। वहाँ एक बार साथी से चैट करें ताकि वह आप तक पहुँच सके।',
  'What is Saathi?': 'साथी क्या है?',
  'Saathi is a guide for Indian government paperwork: PAN, Aadhaar, driving licence, passport, voter ID, GST and state certificates. It explains each step, checks your documents and gets your details ready to copy. You finish on the official website.': 'साथी भारत के सरकारी कागज़ात का गाइड है: पैन, आधार, ड्राइविंग लाइसेंस, पासपोर्ट, वोटर आईडी, GST और राज्य के प्रमाण पत्र। यह हर कदम समझाता है, आपके दस्तावेज़ जाँचता है और आपकी जानकारी कॉपी के लिए तैयार करता है। आखिरी काम आप आधिकारिक वेबसाइट पर करते हैं।',
  'Is Saathi a government service?': 'क्या साथी सरकारी सेवा है?',
  'No. Saathi is independent and not connected to any government body. It always points you to the official website for the final step.': 'नहीं। साथी स्वतंत्र है और किसी सरकारी संस्था से जुड़ा नहीं है। आखिरी कदम के लिए यह हमेशा आपको आधिकारिक वेबसाइट पर भेजता है।',
  'Does Saathi ask for my OTP or password?': 'क्या साथी मेरा OTP या पासवर्ड माँगता है?',
  'Never. If a message asks you for an OTP, PIN or password, it is not from Saathi. Enter those only on the official site.': 'कभी नहीं। अगर कोई मैसेज OTP, PIN या पासवर्ड माँगे तो वह साथी का नहीं है। इन्हें सिर्फ़ आधिकारिक साइट पर डालें।',
  'What does it cost?': 'इसमें कितना खर्च आता है?',
  'You get free guide messages and free AI answers every day, and new people get a small welcome credit. After that each paid feature has a small price you can see in Wallet. A pack covers a whole paperwork job for a few days.': 'हर दिन मुफ़्त गाइड मैसेज और मुफ़्त AI जवाब मिलते हैं, और नए लोगों को थोड़ा स्वागत क्रेडिट मिलता है। उसके बाद हर सशुल्क सुविधा की छोटी कीमत वॉलेट में दिखती है। एक पैक कुछ दिनों के लिए पूरा कागज़ी काम कवर करता है।',
  'Is my data safe?': 'क्या मेरा डेटा सुरक्षित है?',
  'Saved details and the locker are encrypted on our server and only kept if you choose. Your chats are saved on this device only, and you can delete them any time. You can delete everything in Settings.': 'सेव की हुई जानकारी और लॉकर हमारे सर्वर पर एन्क्रिप्ट रहते हैं और तभी रखे जाते हैं जब आप चाहें। आपकी चैट सिर्फ़ इस डिवाइस पर सेव होती है और आप उन्हें कभी भी हटा सकते हैं। सब कुछ सेटिंग्स में हटाया जा सकता है।',
  'Which languages work?': 'कौन सी भाषाएँ चलती हैं?',
  'The whole app works in all the official Indian languages. Saathi answers in the language you write in, so you can switch between English and Hindi mid-chat. Some languages are translated by AI, so check important details.': 'पूरा ऐप सभी आधिकारिक भारतीय भाषाओं में चलता है। साथी उसी भाषा में जवाब देता है जिसमें आप लिखते हैं, इसलिए बातचीत के बीच अंग्रेज़ी और हिंदी बदल सकते हैं। कुछ भाषाएँ AI से अनुवादित हैं, इसलिए ज़रूरी बातें दोबारा जाँच लें।',
  'My payment did not show up': 'मेरा भुगतान नहीं दिखा',
  'It can take a minute. Open Wallet and use “I have paid, check now”. If the money left your account and the wallet stays the same, message us on WhatsApp with your payment receipt.': 'एक मिनट लग सकता है। वॉलेट खोलें और “मैंने भुगतान कर दिया, अभी जाँचें” दबाएँ। अगर पैसे कट गए और वॉलेट वैसा ही रहा, तो भुगतान की रसीद के साथ हमें WhatsApp पर लिखें।',
  'How do I delete my data?': 'मैं अपना डेटा कैसे हटाऊँ?',
  'Settings, then Delete all my data. It removes your saved details, locker, reminders and wallet from our server.': 'सेटिंग्स में जाएँ, फिर “मेरा सारा डेटा हटाएँ”। इससे आपकी सेव जानकारी, लॉकर, रिमाइंडर और वॉलेट हमारे सर्वर से हट जाते हैं।',
  'Answers to the questions people ask most.': 'सबसे ज़्यादा पूछे जाने वाले सवालों के जवाब।',
  'Common questions': 'आम सवाल',
  'Chat on WhatsApp': 'WhatsApp पर चैट करें',
  'Same Saathi, in your WhatsApp': 'वही साथी, आपके WhatsApp में',
  'Where our facts come from': 'हमारी जानकारी कहाँ से आती है',
  'Official sources and when we last checked': 'आधिकारिक स्रोत और हमने आखिरी बार कब जाँचा',
  'Where do your facts come from?': 'आपकी जानकारी कहाँ से आती है?',
  'More': 'और',
  'Auto': 'ऑटो',
  'Light': 'हल्का',
  'Dark': 'गहरा',
  'Normal': 'सामान्य',
  'Large': 'बड़ा',
  'Huge': 'बहुत बड़ा',
  'Preferences': 'पसंद',
  'Appearance': 'रूप-रंग',
  'Style': 'शैली',
  'Classic': 'क्लासिक',
  'Sky': 'आसमान',
  'Check': 'देखें',
  'Open': 'खोलें',
  'For you': 'आपके लिए',
  'What you need': 'आपको क्या चाहिए',
  'Fill it': 'भरें',
  'A saved document expires soon': 'एक सहेजा दस्तावेज़ जल्द ख़त्म होगा',
  'Open your locker': 'अपना लॉकर खोलें',
  'Continue your guide': 'अपना गाइड जारी रखें',
  '{n} steps done': '{n} चरण पूरे',
  'Save your details once': 'अपने विवरण एक बार सहेजें',
  'Then every form is a copy and paste away': 'फिर हर फ़ॉर्म बस कॉपी-पेस्ट का काम है',
  'Fill it with me': 'मेरे साथ भरें',
  'Saathi reads out each value in the order the form asks. You paste it into the official site.': 'साथी फ़ॉर्म के क्रम में हर जानकारी सामने रखता है। आप उसे सरकारी वेबसाइट पर पेस्ट करें।',
  'Start': 'शुरू करें',
  'Back': 'पीछे',
  'Copy and next': 'कॉपी करें, आगे बढ़ें',
  'Copy and finish': 'कॉपी करें और पूरा करें',
  '{i} of {n}': '{n} में से {i}',
  'Tap the box on the website that says "{label}", paste, then come back.': 'वेबसाइट पर "{label}" वाले बॉक्स को दबाएँ, पेस्ट करें, फिर यहाँ लौटें।',
  'Text size': 'अक्षर का आकार',
  'Money': 'पैसे',
  'Transaction history': 'लेन-देन का इतिहास',
  'Your things': 'आपकी चीज़ें',
  'Chats': 'चैट',
  'In use': 'इस्तेमाल में',
  'Empty': 'खाली',
  'Saved': 'सेव है',
  'None': 'कुछ नहीं',
  'Add to Home Screen': 'होम स्क्रीन पर जोड़ें',
  'Tap Share, then Add to Home Screen': 'शेयर दबाएँ, फिर “होम स्क्रीन पर जोड़ें”',
  'Install Saathi': 'साथी इंस्टॉल करें',
  'Open it like an app': 'इसे ऐप की तरह खोलें',
  'Use your browser menu, then Install app.': 'ब्राउज़र मेन्यू खोलें, फिर “ऐप इंस्टॉल करें”।',
  'Privacy and backup': 'गोपनीयता और बैकअप',
  'Backup and restore': 'बैकअप और रीस्टोर',
  'Move your wallet to a new phone': 'अपना वॉलेट नए फ़ोन पर ले जाएँ',
  'Privacy notice': 'गोपनीयता सूचना',
  'Help': 'मदद',
  'Data': 'डेटा',
  'Delete all my chats': 'मेरी सारी चैट हटाएँ',
  'Delete all my data': 'मेरा सारा डेटा हटाएँ',
  'Removes saved details, locker, reminders and wallet': 'सेव जानकारी, लॉकर, रिमाइंडर और वॉलेट हटाता है',
  'Saathi 1.0 · Independent, not a government website': 'साथी 1.0 · स्वतंत्र, सरकारी वेबसाइट नहीं',
  'Your balance and saved details belong to this device. Keep this code somewhere safe to restore them on a new phone or after clearing your browser.': 'आपका बैलेंस और सेव की हुई जानकारी इसी डिवाइस की है। नए फ़ोन पर या ब्राउज़र साफ़ करने के बाद इन्हें वापस पाने के लिए यह कोड सुरक्षित जगह रखें।',
  'Your recovery code': 'आपका रिकवरी कोड',
  'Copy code': 'कोड कॉपी करें',
  'Anyone with this code can use your balance. Never share it.': 'इस कोड वाला कोई भी आपका बैलेंस इस्तेमाल कर सकता है। इसे कभी साझा न करें।',
  'Paste a code to restore': 'रीस्टोर के लिए कोड पेस्ट करें',
  'Recovery code': 'रिकवरी कोड',
  'Restore': 'रीस्टोर करें',
  'That code does not look right.': 'यह कोड सही नहीं लग रहा।',
  'Restore from a code': 'कोड से रीस्टोर करें',
  'Delete all your data?': 'आपका सारा डेटा हटाएँ?',
  'This removes your saved details, locker, reminders and wallet balance from our server, and your chats from this device. It cannot be undone.': 'इससे आपकी सेव जानकारी, लॉकर, रिमाइंडर और वॉलेट बैलेंस हमारे सर्वर से, और आपकी चैट इस डिवाइस से हट जाएँगी। इसे वापस नहीं किया जा सकता।',
  'Delete everything': 'सब कुछ हटाएँ',
  'Ask in your own words': 'अपने शब्दों में पूछिए',
  'Type or speak, in your language. Saathi explains PAN, Aadhaar, driving licence, passport and more, one simple step at a time.': 'अपनी भाषा में लिखिए या बोलिए। साथी पैन, आधार, ड्राइविंग लाइसेंस, पासपोर्ट और बहुत कुछ एक-एक आसान कदम में समझाता है।',
  'Check documents before you apply': 'आवेदन से पहले दस्तावेज़ जाँचें',
  'Snap a photo or upload a PDF. Saathi spots blur, glare and mistakes, and gets your details ready to copy.': 'फ़ोटो खींचिए या PDF डालिए। साथी धुंधलापन, चमक और गलतियाँ पकड़ता है और आपकी जानकारी कॉपी के लिए तैयार करता है।',
  'Private, and never asks for your OTP': 'निजी, और कभी आपका OTP नहीं माँगता',
  'No sign-up. Your locker is encrypted and hidden until you unlock it. You always finish on the official website.': 'साइन-अप की ज़रूरत नहीं। आपका लॉकर एन्क्रिप्ट रहता है और अनलॉक करने तक छिपा रहता है। आखिरी काम आप हमेशा आधिकारिक वेबसाइट पर करते हैं।',
  'Skip': 'छोड़ें',
  'How your data is handled': 'आपका डेटा कैसे संभाला जाता है',
  'Free to start, no sign-up.': 'शुरू करना मुफ़्त, साइन-अप नहीं।',
  'Choose your language': 'अपनी भाषा चुनें',
  'The whole app will show in it. You can change it any time in Settings.': 'पूरा ऐप इसी में दिखेगा। आप इसे कभी भी सेटिंग्स में बदल सकते हैं।',
  'Continue in {lang}': '{lang} में आगे बढ़ें',
  'Next': 'आगे',
  'What do you need help with?': 'आपको किस चीज़ में मदद चाहिए?',
  'Pick any, or skip. This only decides which questions Saathi suggests first.': 'जो चाहें चुनें, या छोड़ दें। इससे बस तय होता है कि साथी पहले कौन से सवाल सुझाए।',
  'Start chatting': 'चैट शुरू करें',
  'Getting ready…': 'तैयार हो रहा है…',
  'Menu': 'मेन्यू',
  'Open menu': 'मेन्यू खोलें',
  'Open wallet': 'वॉलेट खोलें',
  'Conversation': 'बातचीत',
  'Attach a photo or PDF': 'फ़ोटो या PDF जोड़ें',
  'Take a photo': 'फ़ोटो खींचें',
  'Choose photo or PDF': 'फ़ोटो या PDF चुनें',
  'Ask Saathi anything': 'साथी से कुछ भी पूछिए',
  'Message': 'मैसेज',
  'Speak instead of typing': 'टाइप करने की जगह बोलिए',
  'Saathi guides you. You do the final steps on the official site. Never share your OTP with anyone.': 'साथी आपको रास्ता दिखाता है। आखिरी कदम आप आधिकारिक साइट पर उठाते हैं। अपना OTP किसी को न बताएँ।',
  'Jump to latest message': 'सबसे नए मैसेज पर जाएँ',
  'Welcome to Saathi': 'साथी में आपका स्वागत है',
  'Documents needed': 'ज़रूरी दस्तावेज़',
  'Fee and cost': 'फीस और खर्च',
  'Make a form sheet': 'फ़ॉर्म शीट बनाएँ',
  'Set a reminder': 'रिमाइंडर लगाएँ',
  'Check a message': 'मैसेज जाँचें',
  "English text": "अंग्रेज़ी टेक्स्ट",
  "What do you need help with today?": "आज आपको किस चीज़ में मदद चाहिए?",
  "All tools": "सभी टूल",
  "My details": "मेरी जानकारी",
  "Applications": "आवेदन",
  "Photo resizer": "फ़ोटो रीसाइज़र",
  "Guides": "गाइड",
  "All guides": "सभी गाइड",
  "Devices and sync": "डिवाइस और सिंक",
  "Pick a guide to see what you need, the fee and the official sites.": "गाइड चुनें और देखें कि क्या चाहिए, कितनी फीस है और आधिकारिक साइट कौन सी है।",
  "Get started": "शुरू करें",
  "That number does not look right. Check it and try again.": "यह नंबर सही नहीं लग रहा। जाँचकर फिर कोशिश करें।",
  "That date does not look right.": "यह तारीख़ सही नहीं लग रही।",
  "Pick a document type.": "दस्तावेज़ का प्रकार चुनें।",
  "Give it a short name.": "एक छोटा नाम दें।",
  "Add a number or an expiry date.": "नंबर या समाप्ति तारीख़ जोड़ें।",
  "This document has no expiry date.": "इस दस्तावेज़ की कोई समाप्ति तारीख़ नहीं है।",
  "You have reached the limit. Remove one first.": "सीमा पूरी हो गई। पहले एक हटाएँ।",
  "That is too big.": "यह बहुत बड़ा है।",
  "That code is not right, or it has expired. Ask for a new one.": "कोड ग़लत है या उसकी अवधि खत्म हो गई। नया कोड माँगें।",
  "This is the same device.": "यह वही डिवाइस है।",
  "This device is already linked. Unlink it first.": "यह डिवाइस पहले से जुड़ा है। पहले इसे अनलिंक करें।",
  "Other devices are linked to this one. Sign them out first.": "इससे दूसरे डिवाइस जुड़े हैं। पहले उन्हें साइन आउट करें।",
  "You can link up to 5 devices. Remove one first.": "आप 5 डिवाइस तक जोड़ सकते हैं। पहले एक हटाएँ।",
  "That took too long. Please scan again.": "बहुत देर लग गई। कृपया दोबारा स्कैन करें।",
  "Could not reach Saathi. Check your internet and try again.": "साथी तक नहीं पहुँच पाए। इंटरनेट जाँचकर फिर कोशिश करें।",
  "Something went wrong. Please try again.": "कुछ गड़बड़ हो गई। कृपया फिर कोशिश करें।",
  "GSTIN": "GSTIN",
  "Full name (as on Aadhaar)": "पूरा नाम (आधार के अनुसार)",
  "Date of birth": "जन्म तारीख़",
  "Gender": "लिंग",
  "Address": "पता",
  "PIN code": "पिन कोड",
  "Mobile number": "मोबाइल नंबर",
  "Email": "ईमेल",
  "Add money to continue": "जारी रखने के लिए पैसे जोड़ें",
  "This needs {price}, and your balance is lower. Add money or get a pack.": "इसके लिए {price} चाहिए और आपका बैलेंस कम है। पैसे जोड़ें या पैक लें।",
  "Not now": "अभी नहीं",
  "Everything Saathi can do for you, on its own page. No chat needed.": "साथी जो कुछ कर सकता है, सब अपने अलग पेज पर। चैट की ज़रूरत नहीं।",
  "{doc} expires {when}": "{doc} की समाप्ति {when}",
  "Tap to see your locker": "अपना लॉकर देखने के लिए टैप करें",
  "Check a photo and pull out the details": "फ़ोटो जाँचें और जानकारी निकालें",
  "{n} saved": "{n} सेव",
  "IDs and expiry dates": "आईडी और समाप्ति तारीख़ें",
  "{filled} of {total} filled": "{total} में से {filled} भरे",
  "{label}: {when}": "{label}: {when}",
  "Never miss a date": "कोई तारीख़ न चूकें",
  "{n} tracked": "{n} ट्रैक हो रहे",
  "Track what you applied for": "जो आवेदन किया, उसे ट्रैक करें",
  "Photo or signature to the size a form wants": "फ़ॉर्म की माँग के साइज़ में फ़ोटो या हस्ताक्षर",
  "Check a suspicious message or link": "संदिग्ध मैसेज या लिंक जाँचें",
  "{n} linked": "{n} जुड़े हैं",
  "Use Saathi on your phone too": "साथी अपने फ़ोन पर भी इस्तेमाल करें",
  "Checking the photo is sharp": "फ़ोटो साफ़ है या नहीं, जाँच रहे हैं",
  "Reading the text": "टेक्स्ट पढ़ रहे हैं",
  "Finding names and dates": "नाम और तारीख़ें खोज रहे हैं",
  "Almost done": "लगभग हो गया",
  "Take a photo or upload a PDF. Saathi checks it and pulls out the details.": "फ़ोटो लें या PDF अपलोड करें। साथी उसे जाँचकर जानकारी निकाल देगा।",
  "Free with a pack. Otherwise {price} per scan, only if it reads.": "पैक के साथ मुफ़्त। वरना हर स्कैन {price}, सिर्फ़ तब जब वह पढ़ा जाए।",
  "An AI reads the photo. It is used once and never saved. Your ID numbers go to your locker only if you choose.": "एक AI फ़ोटो पढ़ता है। यह सिर्फ़ एक बार इस्तेमाल होती है और सेव नहीं होती। आपके आईडी नंबर तभी लॉकर में जाएँगे जब आप चाहें।",
  "Place your document flat": "दस्तावेज़ को समतल रखें",
  "Good light, all four corners in view": "अच्छी रोशनी, चारों कोने दिखें",
  "PDF document": "PDF दस्तावेज़",
  "Could not read it": "पढ़ नहीं पाए",
  "Let Saathi read this?": "साथी को यह पढ़ने दें?",
  "An AI reads your photo to find the details. It is used once and not saved. Do not scan anything you would not want a third party to see.": "एक AI आपकी फ़ोटो से जानकारी निकालता है। यह एक बार इस्तेमाल होती है और सेव नहीं होती। ऐसा कुछ स्कैन न करें जो आप किसी तीसरे को दिखाना न चाहें।",
  "Yes, read it": "हाँ, पढ़ो",
  "Pick a photo or a PDF.": "फ़ोटो या PDF चुनें।",
  "That photo is not clear enough to read.": "यह फ़ोटो पढ़ने लायक साफ़ नहीं है।",
  "I could not find any details on it.": "इसमें कोई जानकारी नहीं मिली।",
  "Scanning is busy right now. Please try again in a little while.": "स्कैनिंग अभी व्यस्त है। थोड़ी देर बाद फिर कोशिश करें।",
  "That file is too big. Use one under 5 MB.": "फ़ाइल बहुत बड़ी है। 5 MB से छोटी फ़ाइल इस्तेमाल करें।",
  "Something went wrong reading it. You were not charged.": "पढ़ने में गड़बड़ हुई। आपसे कोई पैसा नहीं लिया गया।",
  "Tips: flat surface, no glare, all corners visible.": "सुझाव: समतल जगह, चमक नहीं, सभी कोने दिखें।",
  "Readable, but: {list}": "पढ़ने लायक है, लेकिन: {list}",
  "Readable and clear": "पढ़ने लायक और साफ़",
  "Number": "नंबर",
  "Expires": "समाप्ति",
  "Save to locker and details": "लॉकर और जानकारी में सेव करें",
  "Save to my locker": "मेरे लॉकर में सेव करें",
  "Save to my details": "मेरी जानकारी में सेव करें",
  "Scan another": "एक और स्कैन करें",
  "Tip: after saving, set a reminder for the expiry date in Reminders.": "सुझाव: सेव करने के बाद रिमाइंडर में समाप्ति तारीख़ का रिमाइंडर लगाएँ।",
  "Keep the numbers and expiry dates of your IDs. Numbers stay hidden until you tap the eye.": "अपनी आईडी के नंबर और समाप्ति तारीख़ें रखें। नंबर आँख पर टैप करने तक छिपे रहते हैं।",
  "Add a document": "दस्तावेज़ जोड़ें",
  "Scan one": "स्कैन करें",
  "Add your PAN, licence or passport. Saathi shows what is about to expire.": "अपना पैन, लाइसेंस या पासपोर्ट जोड़ें। साथी दिखाएगा कि क्या जल्दी खत्म होने वाला है।",
  "Encrypted before it is saved": "सेव होने से पहले एन्क्रिप्ट होता है",
  "Hidden until you tap the eye, and hidden again after 20 seconds": "आँख पर टैप करने तक छिपा रहता है, और 20 सेकंड बाद फिर छिप जाता है",
  "Never shown in a chat, never sent to the AI": "चैट में कभी नहीं दिखता, AI को कभी नहीं भेजा जाता",
  "Delete any document, or everything, at any time": "कभी भी कोई दस्तावेज़ या सब कुछ हटाएँ",
  "No number saved": "कोई नंबर सेव नहीं",
  "Show number": "नंबर दिखाएँ",
  "Expires {date}": "समाप्ति {date}",
  "Remind me": "मुझे याद दिलाएँ",
  "{doc} expires": "{doc} की समाप्ति",
  "Reminder set": "रिमाइंडर लग गया",
  "Delete": "हटाएँ",
  "Delete this document?": "यह दस्तावेज़ हटाएँ?",
  "{doc} will be removed from your locker.": "{doc} आपके लॉकर से हटा दिया जाएगा।",
  "Hide number": "नंबर छिपाएँ",
  "Document type": "दस्तावेज़ का प्रकार",
  "Expiry date": "समाप्ति तारीख़",
  "Document": "दस्तावेज़",
  "Save": "सेव करें",
  "What forms keep asking for. Saved once, ready to copy any time.": "जो फ़ॉर्म बार-बार माँगते हैं। एक बार सेव करें, कभी भी कॉपी करें।",
  "Could not load": "लोड नहीं हो सका",
  "Save details": "जानकारी सेव करें",
  "Some fields do not look right. Check the marked ones.": "कुछ जानकारी सही नहीं लग रही। चिह्नित वाली जाँचें।",
  "Copy everything": "सब कुछ कॉपी करें",
  "Stored encrypted. Never sent to the AI. Delete it any time in Settings.": "एन्क्रिप्ट करके सेव होती है। AI को कभी नहीं भेजी जाती। सेटिंग्स में कभी भी हटाएँ।",
  "Add a date you cannot afford to miss. It shows here, and on WhatsApp if you connect it.": "ऐसी तारीख़ जोड़ें जिसे आप चूक नहीं सकते। यह यहाँ दिखेगी, और WhatsApp जोड़ने पर वहाँ भी।",
  "What is it? (for example, Licence renewal)": "यह क्या है? (जैसे, लाइसेंस नवीनीकरण)",
  "Reminder name": "रिमाइंडर का नाम",
  "Date": "तारीख़",
  "Add reminder": "रिमाइंडर जोड़ें",
  "New reminder": "नया रिमाइंडर",
  "{doc} expires {date}": "{doc} की समाप्ति {date}",
  "From your locker": "आपके लॉकर से",
  "Remove this reminder?": "यह रिमाइंडर हटाएँ?",
  "Remove": "हटाएँ",
  "Coming up": "आगामी",
  "Reminders also arrive on your WhatsApp: 30 days before, 7 days before and on the day.": "रिमाइंडर WhatsApp पर भी आते हैं: 30 दिन पहले, 7 दिन पहले और उसी दिन।",
  "Get these on WhatsApp too. Connect your phone in Devices and sync.": "ये WhatsApp पर भी पाएँ। डिवाइस और सिंक में अपना फ़ोन जोड़ें।",
  "Preparing": "तैयारी में",
  "Applied": "आवेदन किया",
  "Waiting": "इंतज़ार में",
  "Keep track of what you applied for, with the reference number and where it stands.": "जो आवेदन किया उसका रेफ़रेंस नंबर और स्थिति ट्रैक करें।",
  "Track an application": "आवेदन ट्रैक करें",
  "Nothing tracked yet": "अभी कुछ ट्रैक नहीं हो रहा",
  "Add an application to keep its reference number and status in one place.": "आवेदन जोड़ें ताकि उसका रेफ़रेंस नंबर और स्थिति एक जगह रहे।",
  "Application": "आवेदन",
  "Ref: {ref}": "रेफ़: {ref}",
  "Official site": "आधिकारिक साइट",
  "Copy ref": "रेफ़ कॉपी करें",
  "Edit": "बदलें",
  "Delete this?": "यह हटाएँ?",
  "Service": "सेवा",
  "Something else": "कुछ और",
  "Name (for example, PAN correction)": "नाम (जैसे, पैन सुधार)",
  "Reference or acknowledgement number": "रेफ़रेंस या पावती नंबर",
  "Note (optional)": "नोट (वैकल्पिक)",
  "Name": "नाम",
  "Reference number": "रेफ़रेंस नंबर",
  "Date applied": "आवेदन की तारीख़",
  "Note": "नोट",
  "Edit application": "आवेदन बदलें",
  "Make a photo or signature the size a form asks for. It never leaves your phone.": "फ़ोटो या हस्ताक्षर को फ़ॉर्म के माँगे साइज़ में बनाएँ। यह आपके फ़ोन से बाहर नहीं जाता।",
  "Choose a photo": "फ़ोटो चुनें",
  "Size in pixels": "पिक्सल में साइज़",
  "Keep the size": "साइज़ वही रखें",
  "Passport photo, 3.5 × 4.5 cm": "पासपोर्ट फ़ोटो, 3.5 × 4.5 सेमी",
  "Square, 512 × 512": "चौकोर, 512 × 512",
  "Custom size": "अपना साइज़",
  "Width px": "चौड़ाई px",
  "Height px": "ऊँचाई px",
  "Resize": "रीसाइज़ करें",
  "Keep it under": "इससे छोटा रखें",
  "Check the size and format the official form asks for. Different forms ask for different sizes.": "आधिकारिक फ़ॉर्म जो साइज़ और फ़ॉर्मैट माँगे, वह जाँचें। अलग फ़ॉर्म अलग साइज़ माँगते हैं।",
  "Could not open that photo. Try a JPEG or PNG.": "वह फ़ोटो खुल नहीं सकी। JPEG या PNG आज़माएँ।",
  "Original: {w} × {h}, {kb} KB": "मूल: {w} × {h}, {kb} KB",
  "Enter a width and height between 50 and 6000.": "50 से 6000 के बीच चौड़ाई और ऊँचाई डालें।",
  "Could not get it that small. Try a bigger limit.": "इतना छोटा नहीं हो सका। बड़ी सीमा आज़माएँ।",
  "Download": "डाउनलोड",
  "Done: {w} × {h}, {kb} KB": "हो गया: {w} × {h}, {kb} KB",
  "Closest it can get: {kb} KB. Try a bigger limit or a smaller size.": "सबसे पास यह पहुँचा: {kb} KB। बड़ी सीमा या छोटा साइज़ आज़माएँ।",
  "Use the same Saathi on your phone and computer. Your locker, details, reminders, applications and wallet follow you.": "फ़ोन और कंप्यूटर पर वही साथी इस्तेमाल करें। आपका लॉकर, जानकारी, रिमाइंडर, आवेदन और वॉलेट साथ चलते हैं।",
  "Not available here": "यहाँ उपलब्ध नहीं",
  "Linking devices needs the live Saathi server.": "डिवाइस जोड़ने के लिए लाइव साथी सर्वर चाहिए।",
  "This device": "यह डिवाइस",
  "Remove this device?": "यह डिवाइस हटाएँ?",
  "{label} will lose access right away. Its data here stays safe.": "{label} की पहुँच तुरंत बंद हो जाएगी। यहाँ का डेटा सुरक्षित रहेगा।",
  "Main": "मुख्य",
  "Linked {date}": "जुड़ा {date}",
  "First device": "पहला डिवाइस",
  "Your devices": "आपके डिवाइस",
  "Add another device": "दूसरा डिवाइस जोड़ें",
  "Open Saathi on the other device, go to Devices and sync, and enter this code. It works once and expires in 5 minutes.": "दूसरे डिवाइस पर साथी खोलें, डिवाइस और सिंक में जाएँ और यह कोड डालें। यह एक बार चलता है और 5 मिनट में खत्म हो जाता है।",
  "Expires in {m}:{s}": "{m}:{s} में खत्म",
  "Copy link": "लिंक कॉपी करें",
  "Show a code": "कोड दिखाएँ",
  "Have a code from another device?": "दूसरे डिवाइस से कोड मिला है?",
  "Code": "कोड",
  "Link this device": "यह डिवाइस जोड़ें",
  "Link this device?": "यह डिवाइस जोड़ें?",
  "This device will use the account of the other device. Anything saved only here (wallet balance, locker, details) will be replaced by that account’s data.": "यह डिवाइस दूसरे डिवाइस का अकाउंट इस्तेमाल करेगा। जो सिर्फ़ यहाँ सेव है (वॉलेट बैलेंस, लॉकर, जानकारी) वह उस अकाउंट के डेटा से बदल जाएगा।",
  "Link": "जोड़ें",
  "Linked": "जुड़ गया",
  "Connect your WhatsApp": "अपना WhatsApp जोड़ें",
  "Your WhatsApp is connected. Reminders arrive there and the same locker, details and wallet are used in both places.": "आपका WhatsApp जुड़ा है। रिमाइंडर वहाँ आते हैं और दोनों जगह एक ही लॉकर, जानकारी और वॉलेट इस्तेमाल होते हैं।",
  "Disconnect WhatsApp": "WhatsApp हटाएँ",
  "Disconnect WhatsApp?": "WhatsApp हटाएँ?",
  "Reminders will stop arriving there. Your data stays in your account.": "वहाँ रिमाइंडर आना बंद हो जाएगा। आपका डेटा आपके अकाउंट में रहेगा।",
  "Disconnect": "हटाएँ",
  "Send this exact message to Saathi on WhatsApp from your phone, then tap Yes when it asks.": "अपने फ़ोन से WhatsApp पर साथी को यही मैसेज भेजें, फिर जब पूछे तो हाँ दबाएँ।",
  "Open WhatsApp": "WhatsApp खोलें",
  "I sent it, check now": "मैंने भेज दिया, अभी जाँचें",
  "WhatsApp connected": "WhatsApp जुड़ गया",
  "Not yet. Send the message, tap Yes, then try again.": "अभी नहीं। मैसेज भेजें, हाँ दबाएँ, फिर कोशिश करें।",
  "Get reminders on your phone and use the same account there. WhatsApp itself proves the number is yours, and you confirm with a Yes.": "फ़ोन पर रिमाइंडर पाएँ और वहाँ वही अकाउंट इस्तेमाल करें। WhatsApp खुद साबित करता है कि नंबर आपका है, और आप हाँ से पुष्टि करते हैं।",
  "Connect WhatsApp": "WhatsApp जोड़ें",
  "On": "चालू",
  "Off": "बंद",
  "Chats will sync": "चैट सिंक होंगी",
  "Chats stay on this device": "चैट इसी डिवाइस पर रहेंगी",
  "Sync my chats too": "मेरी चैट भी सिंक करें",
  "Locker, details, reminders, applications and wallet always sync. Chats only sync if you turn this on. They are stored encrypted.": "लॉकर, जानकारी, रिमाइंडर, आवेदन और वॉलेट हमेशा सिंक होते हैं। चैट तभी सिंक होती हैं जब आप इसे चालू करें। वे एन्क्रिप्ट करके रखी जाती हैं।",
  "Sync": "सिंक",
  "A code works once and expires in 5 minutes": "कोड एक बार चलता है और 5 मिनट में खत्म हो जाता है",
  "You confirm on the new device before anything is linked": "कुछ भी जुड़ने से पहले आप नए डिवाइस पर पुष्टि करते हैं",
  "WhatsApp needs a Yes reply from that same phone": "WhatsApp के लिए उसी फ़ोन से हाँ का जवाब चाहिए",
  "Remove any device at any time and it loses access at once": "कभी भी कोई डिवाइस हटाएँ, उसकी पहुँच तुरंत बंद हो जाती है",
  "Nobody can link a device without a code that only you can see": "ऐसे कोड के बिना कोई डिवाइस नहीं जुड़ सकता जो सिर्फ़ आप देख सकते हैं",
  "How linking stays safe": "जोड़ना कैसे सुरक्षित रहता है",
  "Unlink this device": "यह डिवाइस अनलिंक करें",
  "Unlink this device?": "यह डिवाइस अनलिंक करें?",
  "This device will start empty. Your account stays on your other devices.": "यह डिवाइस खाली शुरू होगा। आपका अकाउंट दूसरे डिवाइस पर बना रहेगा।",
  "Unlink": "अनलिंक",
  "Sign out all other devices": "बाकी सभी डिवाइस साइन आउट करें",
  "Sign out other devices?": "बाकी डिवाइस साइन आउट करें?",
  "Every other device loses access right away.": "बाकी सभी डिवाइस की पहुँच तुरंत बंद हो जाएगी।",
  "Sign out": "साइन आउट",
  "Signed out": "साइन आउट हो गए",
  "A recovery code, if you lose this device": "रिकवरी कोड, अगर यह डिवाइस खो जाए",
  "Every fee and step is taken from an official page. When we last checked is shown below.": "हर फीस और स्टेप किसी आधिकारिक पेज से लिया गया है। हमने आख़िरी बार कब जाँचा, यह नीचे दिखता है।",
  "Fees and rules change. Always confirm on the official site before you pay.": "फीस और नियम बदलते रहते हैं। भुगतान से पहले हमेशा आधिकारिक साइट पर पुष्टि करें।",
  "Ask Saathi": "साथी से पूछें",
  "Step-by-step guide": "स्टेप-बाय-स्टेप गाइड",
  "{n} of {total} ready": "{total} में से {n} तैयार",
  "Do it here": "यहीं करें",
  "Check it before you upload": "अपलोड से पहले जाँचें",
  "Track this application": "यह आवेदन ट्रैक करें",
  "Keep the reference number and status": "रेफ़रेंस नंबर और स्थिति सँभालकर रखें",
  "Resize a photo or signature": "फ़ोटो या हस्ताक्षर रीसाइज़ करें",
  "Everything you need in one place": "आपको जो कुछ चाहिए, एक जगह",
  "Documents": "दस्तावेज़",
  "Fee": "फीस",
  "Not saved yet": "अभी सेव नहीं है",
  "Show": "दिखाएँ",
  "Could not open. Try again.": "खुल नहीं पाया। फिर कोशिश करें।",
  "Encrypted. Tap Show to see.": "एन्क्रिप्टेड। देखने के लिए दिखाएँ दबाएँ।",
  "Private values are encrypted and never sit in this chat. They hide again after 20 seconds.": "निजी जानकारी एन्क्रिप्टेड रहती है और चैट में नहीं रखी जाती। 20 सेकंड बाद फिर छिप जाती है।",
  "Continue": "आगे बढ़ें",
  "Tell Saathi about you": "साथी को अपने बारे में बताइए",
  "Saathi fills your forms from these, so you never type them twice. Stored encrypted. Fill in all four to continue, or skip.": "साथी इनसे आपके फ़ॉर्म भरता है, ताकि दोबारा टाइप न करना पड़े। एन्क्रिप्टेड सेव होता है। आगे बढ़ने के लिए चारों भरें, या छोड़ दें।",
  "As on your Aadhaar": "आधार के अनुसार",
  "Age: {n}": "उम्र: {n}",
  "Male": "पुरुष",
  "Female": "महिला",
  "Your state": "आपका राज्य",
  "I don’t know a state like that.": "मुझे ऐसे किसी राज्य का पता नहीं।",
  "Full name": "पूरा नाम",
  "State": "राज्य",
  "I don’t know a state like that. Try the full name of an Indian state.": "मुझे ऐसे किसी राज्य का पता नहीं। किसी भारतीय राज्य का पूरा नाम लिखें।",
  "Some of that does not look right. Check the name and date.": "कुछ जानकारी सही नहीं लग रही। नाम और तारीख जाँचें।",
  "What needs you now, and everything Saathi can do.": "अभी आपको क्या चाहिए, और साथी क्या-क्या कर सकता है।",
  "Search tools and guides": "टूल और गाइड खोजें",
  "{doc} has expired": "{doc} की अवधि खत्म हो गई है",
  "Waiting for {n} days. Check its status.": "{n} दिन से इंतज़ार है। स्थिति देखें।",
  "Needs attention": "ध्यान चाहिए",
  "Nothing needs you right now": "अभी कुछ भी ज़रूरी नहीं है",
  "Dates, documents and applications are all on track.": "तारीखें, दस्तावेज़ और आवेदन सब ठीक चल रहे हैं।",
  "Continue {service}": "{service} जारी रखें",
  "1 step done": "1 कदम पूरा",
  "{n} steps done": "{n} कदम पूरे",
  "Saved {n} of {total}": "{total} में से {n} सहेजे",
  "Nothing found": "कुछ नहीं मिला",
  "Try another word.": "कोई दूसरा शब्द आज़माएँ।",
  "5 letters, 4 digits, 1 letter. For example ABCDE1234F.": "5 अक्षर, 4 अंक, 1 अक्षर। जैसे ABCDE1234F।",
  "12 digits, starting with 2 to 9. Spaces are fine.": "12 अंक, 2 से 9 से शुरू। बीच में स्पेस चलेगा।",
  "State code, RTO number, then the rest. For example MH12 20110012345.": "राज्य कोड, RTO नंबर, फिर बाकी। जैसे MH12 20110012345।",
  "1 letter then 7 digits. For example A1234567.": "1 अक्षर फिर 7 अंक। जैसे A1234567।",
  "3 letters then 7 digits. For example ABC1234567.": "3 अक्षर फिर 7 अंक। जैसे ABC1234567।",
  "15 characters. For example 22AAAAA0000A1Z5.": "15 अक्षर/अंक। जैसे 22AAAAA0000A1Z5।",
  "Everything saved": "सब कुछ सहेजा है",
  "Tap one to add it": "जोड़ने के लिए किसी पर टैप करें",
  "Not saved": "सहेजा नहीं",
  "Expired": "अवधि खत्म",
  "Expiring soon": "जल्द खत्म होगा",
  "Valid": "मान्य",
  "Renew": "रिन्यू करें",
  "Looks right: {pretty}": "सही लग रहा है: {pretty}",
  "This does not look like a valid number yet.": "यह अभी सही नंबर नहीं लग रहा।",
  "Keep typing. Checking as you go.": "लिखते रहें। साथ-साथ जाँच हो रही है।",
  "Identity": "पहचान",
  "Family": "परिवार",
  "Contact": "संपर्क",
  "Ready for": "इनके लिए तैयार",
  "{n}/{total}": "{n}/{total}",
  "Everything this guide asks for is saved": "इस गाइड में जो माँगा जाता है वह सब सहेजा है",
  "Missing: {list}": "बाकी: {list}",
  "Nothing to copy yet.": "अभी कॉपी करने के लिए कुछ नहीं है।",
  "Calendar file saved": "कैलेंडर फ़ाइल सेव हो गई",
  "Could not make the calendar file.": "कैलेंडर फ़ाइल नहीं बन पाई।",
  "Licence renewal": "लाइसेंस रिन्यूअल",
  "Passport renewal": "पासपोर्ट रिन्यूअल",
  "PAN-Aadhaar link check": "PAN-आधार लिंक जाँच",
  "ITR filing (31 July)": "ITR फाइलिंग (31 जुलाई)",
  "ITR filing": "ITR फाइलिंग",
  "ITR filing is due 31 July each year for most people.": "ज़्यादातर लोगों के लिए ITR की आखिरी तारीख हर साल 31 जुलाई है।",
  "Insurance renewal": "बीमा रिन्यूअल",
  "Vehicle PUC": "गाड़ी का PUC",
  "Voter ID check": "वोटर ID जाँच",
  "Repeat every year": "हर साल दोहराएँ",
  "Quick start": "जल्दी शुरू करें",
  "Saathi counts down to this date. If your WhatsApp is linked you get a message 30 days before, 7 days before and on the day.": "साथी इस तारीख़ तक गिनती रखता है। WhatsApp जुड़ा हो तो 30 दिन पहले, 7 दिन पहले और उसी दिन संदेश मिलता है।",
  "Yearly": "सालाना",
  "Done, remind me next year": "हो गया, अगले साल याद दिलाएँ",
  "Mark done": "पूरा हुआ",
  "Moved to next year": "अगले साल पर खिसका दिया",
  "Save changes": "बदलाव सहेजें",
  "Add to calendar": "कैलेंडर में जोड़ें",
  "Marking it done moves it to {date}.": "पूरा करने पर यह {date} पर चला जाएगा।",
  "Overdue": "समय निकल गया",
  "This week": "इस हफ़्ते",
  "This month": "इस महीने",
  "Later": "बाद में",
  "How you get notified": "आपको सूचना कैसे मिलती है",
  "30 days before": "30 दिन पहले",
  "7 days before": "7 दिन पहले",
  "On the day": "उसी दिन",
  "Reminders show here. Link WhatsApp to get them on your phone.": "रिमाइंडर यहाँ दिखते हैं। फ़ोन पर पाने के लिए WhatsApp जोड़ें।",
  "Gather your documents and check that your details match them exactly.": "अपने दस्तावेज़ इकट्ठा करें और देखें कि जानकारी उनसे बिल्कुल मेल खाती है।",
  "Keep your reference number. Most portals let you check status with it.": "अपना रेफ़रेंस नंबर संभालकर रखें। ज़्यादातर पोर्टल इससे स्थिति देखने देते हैं।",
  "Check the status every few days. If nothing changes for a couple of weeks, contact the helpline or office.": "हर कुछ दिन में स्थिति देखें। दो हफ़्ते तक कुछ न बदले तो हेल्पलाइन या दफ़्तर से संपर्क करें।",
  "Keep the final document or receipt safe, and save its number in your locker.": "अंतिम दस्तावेज़ या रसीद सुरक्षित रखें और उसका नंबर अपने लॉकर में सहेजें।",
  "Keep your Aadhaar and a photo ready. Your name should match Aadhaar exactly.": "आधार और फ़ोटो तैयार रखें। आपका नाम आधार से बिल्कुल मिलना चाहिए।",
  "Keep the acknowledgement number. The official site lets you track a PAN application with it.": "पावती नंबर संभालकर रखें। आधिकारिक साइट पर इससे PAN आवेदन ट्रैक कर सकते हैं।",
  "Keep your proof of identity and proof of address ready.": "पहचान प्रमाण और पते का प्रमाण तैयार रखें।",
  "Keep the update request number (URN). You can check the update status with it.": "अपडेट रिक्वेस्ट नंबर (URN) संभालकर रखें। इससे अपडेट की स्थिति देख सकते हैं।",
  "Keep your ID, address proof and a passport-size photo ready.": "अपना ID, पते का प्रमाण और पासपोर्ट साइज़ फ़ोटो तैयार रखें।",
  "Keep the application number. Parivahan lets you check status with it.": "आवेदन नंबर संभालकर रखें। परिवहन साइट पर इससे स्थिति देख सकते हैं।",
  "Keep your original documents ready for the appointment.": "अपॉइंटमेंट के लिए असली दस्तावेज़ तैयार रखें।",
  "Keep the file number. Passport Seva lets you track the application with it.": "फ़ाइल नंबर संभालकर रखें। पासपोर्ट सेवा पर इससे आवेदन ट्रैक कर सकते हैं।",
  "Keep an ID proof and an address proof ready.": "एक पहचान प्रमाण और एक पते का प्रमाण तैयार रखें।",
  "Keep the reference ID. The voter portal lets you track the form with it.": "रेफ़रेंस ID संभालकर रखें। वोटर पोर्टल पर इससे फ़ॉर्म ट्रैक कर सकते हैं।",
  "Keep your PAN, address proof and bank details ready.": "PAN, पते का प्रमाण और बैंक की जानकारी तैयार रखें।",
  "Keep the ARN. The GST portal lets you track the application with it.": "ARN संभालकर रखें। GST पोर्टल पर इससे आवेदन ट्रैक कर सकते हैं।",
  "Check {title}": "{title} जाँचें",
  "Reminder set for 7 days from now": "7 दिन बाद का रिमाइंडर लग गया",
  "Copy reference number": "रेफ़रेंस नंबर कॉपी करें",
  "No reference number yet": "अभी रेफ़रेंस नंबर नहीं है",
  "Status": "स्थिति",
  "Applied {when}": "आवेदन किया: {when}",
  "Waiting {n} days": "{n} दिन से इंतज़ार",
  "Expected by {date}": "अपेक्षित तारीख़: {date}",
  "Next step": "अगला कदम",
  "Remind me to check": "जाँचने की याद दिलाएँ",
  "All": "सभी",
  "Nothing here": "यहाँ कुछ नहीं",
  "No applications in this list.": "इस सूची में कोई आवेदन नहीं है।",
  "Expected by (optional)": "कब तक अपेक्षित (वैकल्पिक)",
  "Loading…": "लोड हो रहा है…",
  "Could not load this guide. Check your internet and try again.": "यह गाइड लोड नहीं हो पाई। इंटरनेट जाँचकर फिर कोशिश करें।",
  "Nothing to apply for. Read the note below.": "आवेदन की ज़रूरत नहीं है। नीचे दिया नोट पढ़ें।",
  "Start by finding your route": "पहले अपना रास्ता चुनें",
  "Every step is done": "सारे स्टेप पूरे हो गए",
  "Step {i} of {n} is next": "अगला स्टेप: {i} / {n}",
  "Start over": "फिर से शुरू करें",
  "Steps": "स्टेप",
  "Fees": "फीस",
  "Start this guide over?": "यह गाइड फिर से शुरू करें?",
  "Your ticked steps and answers for this guide are cleared. Your saved details are not touched.": "इस गाइड के टिक किए स्टेप और जवाब हट जाएँगे। आपकी सेव की गई जानकारी नहीं छुई जाएगी।",
  "Find your route": "अपना रास्ता खोजें",
  "Question {n}": "सवाल {n}",
  "Could not load the question. Try again.": "सवाल लोड नहीं हो पाया। फिर कोशिश करें।",
  "Yes": "हाँ",
  "No": "नहीं",
  "This one has no step-by-step guide yet. Use the tabs for documents and fees, or ask Saathi.": "इसकी स्टेप-बाय-स्टेप गाइड अभी नहीं है। दस्तावेज़ और फीस के टैब देखें, या साथी से पूछें।",
  "Change my answers": "मेरे जवाब बदलें",
  "Your route": "आपका रास्ता",
  "Copy my details": "मेरी जानकारी कॉपी करें",
  "{done} of {n} steps done": "{n} में से {done} स्टेप पूरे",
  "Step {i}": "स्टेप {i}",
  "Done, next step": "हो गया, अगला स्टेप",
  "Ask about this step": "इस स्टेप के बारे में पूछें",
  "I am on step {i} of the {name} guide: \"{text}\". Explain it simply and tell me what to watch out for.": "मैं {name} गाइड के स्टेप {i} पर हूँ: \"{text}\"। इसे आसान भाषा में समझाएँ और बताएँ कि किस बात का ध्यान रखना है।",
  "Explain step {i} of {name}": "{name} का स्टेप {i} समझाएँ",
  "That is every step": "बस, सारे स्टेप हो गए",
  "Remind me before it expires": "एक्सपायर होने से पहले याद दिलाएँ",
  "Watch out for": "इन बातों का ध्यान रखें",
  "Acknowledgement or reference number": "acknowledgement या रेफ़रेंस नंबर",
  "What did you apply for?": "आपने किसके लिए आवेदन किया?",
  "Saved in Applications": "आवेदन में सेव हो गया",
  "Keep the reference number here so you can find it later.": "रेफ़रेंस नंबर यहाँ रखें ताकि बाद में मिल सके।",
  "Set reminder": "रिमाइंडर लगाएँ",
  "You get a notice a month before, a week before, and on the day.": "आपको एक महीने पहले, एक हफ्ते पहले और उसी दिन सूचना मिलेगी।",
  "Nothing saved yet. Fill your details on the My details tab.": "अभी कुछ सेव नहीं है। मेरे विवरण टैब में जानकारी भरें।",
  "{done} of {n} ready": "{n} में से {done} तैयार",
  "In your locker": "आपके लॉकर में है",
  "Add to locker": "लॉकर में जोड़ें",
  "Resize a photo": "फ़ोटो का साइज़ बदलें",
  "You have everything. Go to the Steps tab.": "आपके पास सब कुछ है। स्टेप टैब पर जाएँ।",
  "What it costs": "कितना खर्च होगा",
  "Your portal shows the exact amount before you pay.": "आपका पोर्टल पेमेंट से पहले सही रकम दिखाता है।",
  "Fee calculator": "फीस कैलकुलेटर",
  "Could not work that out. Try again.": "हिसाब नहीं लग पाया। फिर कोशिश करें।",
  "Less": "कम",
  "Shown at payment": "पेमेंट पर दिखेगा",
  "Free": "मुफ्त",
  "Total": "कुल",
  "About {amt}": "करीब {amt}",
  "Total so far": "अब तक कुल",
  "Official wording": "सरकारी विवरण",
  "This guide needs no saved details.": "इस गाइड के लिए कोई सेव की जानकारी नहीं चाहिए।",
  "{done} of {n} saved": "{n} में से {done} सेव",
  "Everything this form asks for is saved. Copy each value as you go.": "इस फॉर्म की सारी जानकारी सेव है। हर वैल्यू कॉपी करके भरते जाएँ।",
  "Fill in what is missing. It is saved encrypted and reused for every form.": "जो कमी है वह भरें। यह एन्क्रिप्टेड सेव होती है और हर फॉर्म में काम आती है।",
  "DD/MM/YYYY": "DD/MM/YYYY",
  "Save what I filled in": "जो भरा है वह सेव करें",
  "Fill in at least one field.": "कम से कम एक खाना भरें।",
  "Stored encrypted. Never sent to the AI.": "एन्क्रिप्टेड सेव होता है। AI को कभी नहीं भेजा जाता।",
  "Official websites": "आधिकारिक वेबसाइटें",
  "Used for {list}": "इनके लिए: {list}",
  "Opens in your browser": "आपके ब्राउज़र में खुलेगा",
  "Scan": "स्कैन करें",
  "Resize": "छोटा करें",
  "Add": "जोड़ें",
  "Got a suspicious call or message? Check if it is a scam.": "कोई शक वाला कॉल या मैसेज आया? जाँचें कि कहीं ठगी तो नहीं।",
  "Scan a document and pull out the details": "दस्तावेज़ स्कैन करें और जानकारी निकालें",
  "Make a photo or signature the size a form wants": "फ़ोटो या दस्तख़त को फ़ॉर्म के साइज़ में बनाएँ",
  "Set a reminder so you never miss a date": "रिमाइंडर लगाएँ ताकि कोई तारीख़ न छूटे",
  "Apply for a PAN card, step by step": "PAN कार्ड के लिए आवेदन करें, स्टेप बाय स्टेप",
  "Fix your Aadhaar details, step by step": "आधार की जानकारी ठीक करें, स्टेप बाय स्टेप",
  "Get a driving licence, step by step": "ड्राइविंग लाइसेंस बनवाएँ, स्टेप बाय स्टेप",
  "Apply for a passport, step by step": "पासपोर्ट के लिए आवेदन करें, स्टेप बाय स्टेप",
  "This language needs Saathi’s AI, which is not switched on yet. Hindi and English work now.": "इस भाषा के लिए साथी का AI चाहिए, जो अभी चालू नहीं है। हिन्दी और अंग्रेज़ी अभी चलती हैं।",
  "Search": "खोजें",
};
